name: Cloudflare Tunnel for RDP

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: windows-2022
    steps:
      - name: Start Cloudflare Tunnel
        shell: pwsh
        run: |
          Write-Host "Starting Cloudflare Tunnel for RDP..."

          # Start cloudflared in background with JSON logs
          Start-Process -FilePath "cloudflared" `
            -ArgumentList "tunnel --url rdp://localhost:3389 --no-autoupdate --logfile $env:TEMP\cf.log --logformat json" `
            -NoNewWindow

          # Give it some time to boot
          Start-Sleep -Seconds 8

          # Extract tunnel URL safely
          $url = (Get-Content "$env:TEMP\cf.log" -Raw | Select-String -Pattern '"hostname"' | ForEach-Object {
              ($_ -split '"hostname":')[1] -split '"' | Select-Object -Index 1
          } | Select-Object -First 1)

          if ([string]::IsNullOrEmpty($url)) {
              Write-Host "⚠️ No tunnel URL found, but process may still be running."
          } else {
              Write-Host "✅ Your tunnel URL is: $url"
          }

          # Keep job alive (tunnel will close if script exits)
          Write-Host "Tunnel is running... press Ctrl+C to stop."
          Start-Sleep -Seconds 3600
