name: macOS Live Runner

on:
  workflow_dispatch:

jobs:
  macos-runner:
    runs-on: macos-latest
    timeout-minutes: 360 # This is the maximum allowed duration for a GitHub-hosted runner

steps:  
  - name: Set up Remote Access on macOS
    run: |
      # Install VNC server using Homebrew
      brew install --cask vnc-server

      # Start the VNC server in the background
      vncserver -localhost no :1

      # Get and print the Tailscale IP
      ts_ip=$(tailscale ip -4)
      echo "TAILSCALE_IP=$ts_ip" >> $GITHUB_ENV

      echo "VNC Server is running on $ts_ip"

      # Keep the job alive
      sleep 3600

      while ($true) {
             Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
             Start-Sleep -Seconds 300
          }
      
   