name: macOS Live Runner

on:
  workflow_dispatch:

jobs:
  macos-runner:
    runs-on: macos-latest
    timeout-minutes: 360 # This is the maximum allowed duration for a GitHub-hosted runner

  steps:  
  - name: Set up Remote Access on macOS
    run: |
      # Install VNC server using Homebrew
      brew install --cask vnc-server

      # Start the VNC server in the background
      vncserver -localhost no :1

      # Get and print the Tailscale IP
      ts_ip=$(tailscale ip -4)
      echo "TAILSCALE_IP=$ts_ip" >> $GITHUB_ENV

      echo "VNC Server is running on $ts_ip"

      # Keep the job alive
      sleep 3600

      
    steps:
    - name: Hold the runner live
      run: |
            echo "This job will stay live for up to 6 hours..."
            # The loop will keep the job running by delaying for 5-minute intervals.
            # It's set to run for 360 minutes total, but the loop is a safeguard.
            for ((i=0; i<360; i+=5)); do
            echo "Runner is still live. Remaining time: $((360 - i)) minutes"
            sleep 300
            done