name: macOS GitHub Runner with Tailscale + VNC

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          brew install tailscale
          sudo /opt/homebrew/opt/tailscale/bin/tailscaled --state=mem: &
          sleep 5
          sudo tailscale up --auth-key=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-macos

      - name: Enable Screen Sharing (VNC)
        run: |
          # Set VNC password (change this or use a secret!)
          VNC_PASS="mypassword"
          echo "$VNC_PASS" | security add-generic-password -a $USER -s vnc-password -w
          # Enable ARD (Apple Remote Desktop)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -users $USER -privs -all -restart -agent -menu
          # Enable VNC password auth
          sudo defaults write /Library/Preferences/com.apple.VNCSettings VNCAlwaysStartOnConsole -bool true
          echo "$VNC_PASS" | iconv -t UTF-16LE | openssl md5 -binary | xxd -p | tr -d '\n' | sudo tee /Library/Preferences/com.apple.VNCSettings.plist >/dev/null
          echo "VNC enabled with password: $VNC_PASS"

      - name: Show Tailscale IP
        run: |
          echo "========== Tailscale Node Info =========="
          tailscale ip
          echo "========================================="
          echo "Connect using: vnc://<tailscale-ip>:5900"
          echo "Password: mypassword"
 
      - name: Keep session alive (6 hours)
        run: sleep 21600
