name: macOS Full Desktop via Tailscale + noVNC

on:
  workflow_dispatch:

jobs:
  macos-desktop:
    runs-on: macos-latest
    timeout-minutes: 360   # 6 hours

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Install and start Tailscale
      - name: Install Tailscale
        run: |
          brew install tailscale
          sudo tailscaled > /tmp/tailscaled.log 2>&1 &
          sleep 5
          sudo tailscale up --ssh --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=github-macos

      - name: Show Tailscale IP
        run: tailscale ip -4

      # 2. Enable macOS built-in Screen Sharing (VNC server)
      - name: Enable VNC on macOS
        run: |
          VNC_PASS="mypassword"  # change or move to secrets
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all
          echo "$VNC_PASS" | security add-generic-password -a runner -s vnc-password -w "$VNC_PASS" -U
          echo "VNC enabled on port 5900 with password: $VNC_PASS"

      # 3. Install and run noVNC for browser access
      - name: Install noVNC
        run: |
          brew install git
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify.git ~/noVNC/utils/websockify
          nohup ~/noVNC/utils/launch.sh --vnc localhost:5900 --listen 6080 > /tmp/novnc.log 2>&1 &

          echo "======================================="
          echo "✅ macOS Desktop is live!"
          echo "Tailscale IP: $(tailscale ip -4)"
          echo "Browser URL (connect via Tailscale VPN):"
          echo "    http://$(tailscale ip -4):6080/vnc.html"
          echo "======================================="

      # 4. Keep workflow alive for 6 hours
      - name: Keep Alive
        run: sleep 21600
