name: macOS GitHub Runner with Tailscale + VNC

on:
  workflow_dispatch:

jobs:
  macos-vnc:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          brew install tailscale
          sudo tailscaled --state=mem: --socket=/tmp/tailscaled.sock &
          sleep 5
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --socket=/tmp/tailscaled.sock --hostname=github-macos

      - name: Setup VNC server
        run: |
          # Set VNC password
          echo "mypassword" | security add-generic-password -a $USER -s vnc-password -w
          # Enable Screen Sharing (VNC)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -users $USER -privs -all -restart -agent -menu
          # Allow VNC clients with password
          sudo defaults write /Library/Preferences/com.apple.VNCSettings VNCAlwaysStartOnConsole -bool true
          sudo defaults write /Library/Preferences/com.apple.VNCSettings Password -data $(echo -n "mypassword" | base64)
          echo "VNC enabled with password 'mypassword'"

      - name: Show Tailscale IP
        run: |
          echo "========== Tailscale Node Info =========="
          tailscale ip --socket=/tmp/tailscaled.sock
          echo "========================================="
          echo "Connect with a VNC client to above Tailscale IP (port 5900)."
          echo "Password: mypassword"
          echo "Session will stay alive for 6 hours."

      - name: Keep session alive (6 hours)
        run: sleep 21600
