name: macOS Desktop with Browser Access (noVNC + Tailscale)

on:
  workflow_dispatch:

jobs:
  macos-desktop:
    runs-on: macos-latest
    timeout-minutes: 360   # 6 hours max runtime

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Install Tailscale
      - name: Install Tailscale
        run: |
          brew install tailscale

      - name: Start Tailscale
        run: |
          sudo tailscaled > /tmp/tailscaled.log 2>&1 &
          sleep 5

      - name: Authenticate to Tailscale
        run: |
          sudo tailscale up --ssh --hostname=github-macos --accept-routes --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Show Tailscale Status
        run: |
          echo "Tailscale IPv4:"
          tailscale ip -4
          tailscale status

      # 2. Install noVNC + x11vnc
      - name: Install Desktop Tools
        run: |
          brew install xquartz x11vnc
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify.git ~/noVNC/utils/websockify

      # 3. Start Virtual Display + VNC + noVNC
      - name: Start Desktop Services
        run: |
          nohup Xvfb :1 -screen 0 1280x720x24 > /tmp/xvfb.log 2>&1 &
          export DISPLAY=:1

          # Start x11vnc
          x11vnc -display :1 -nopw -forever -rfbport 5901 > /tmp/x11vnc.log 2>&1 &

          # Start noVNC proxy (uses built-in websockify)
          ~/noVNC/utils/launch.sh --vnc localhost:5901 --listen 6080 > /tmp/novnc.log 2>&1 &

          echo "Services started!"

      - name: Access Information
        run: |
          echo "======================================="
          echo "✅ noVNC is running!"
          echo "Open this in your browser (while connected to Tailscale):"
          echo "    http://<Tailscale-IP>:6080/vnc.html"
          echo "======================================="
      # 4. Keep runner alive (6 hours max)
      - name: Keep Alive
        run: |
          echo "Keeping macOS desktop alive for 6 hours..."
          sleep 21600