name: macOS VNC via Tailscale

on:
  workflow_dispatch:

jobs:
  vnc:
    runs-on: macos-latest
    steps:
      - name: Install Tailscale
        run: |
          brew install --cask tailscale
          sudo tailscaled > /tmp/tailscaled.log 2>&1 &
          sleep 5
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname github-macos-runner
          echo "✅ Tailscale started"
          tailscale ip -4

      - name: Enable VNC server
        run: |
          echo "Setting VNC password..."
          VNC_PASS="mypassword"   # 🔑 Change this to your own password
          
          # Enable Remote Management
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -restart -agent -privs -all
          
          # Set VNC password
          sudo defaults write /Library/Preferences/com.apple.RemoteManagement VNCAlwaysStart -bool true
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Support/VNCPasswordTool -set "$VNC_PASS"
          
          echo "✅ VNC Enabled with password: $VNC_PASS"
          echo "👉 Connect using: vnc://$(tailscale ip -4):5900"

      - name: Keep Alive for 6h
        run: |
          echo "========================================="
          echo "✅ macOS VNC is ready!"
          echo "Connect from any Tailscale device:"
          echo "   vnc://$(tailscale ip -4):5900"
          echo "Password = mypassword"
          echo "========================================="
          sleep 21600
